spring:
  mail:
    host: smtp.gmail.com
    prot: 587
    username: dldusdn8060@gmail.com
    password: aalminfmrxqfglgg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB